"""create_core_domain_schema

Revision ID: cd73103ae9e0
Revises: 
Create Date: 2026-09-12 05:40:47.992707

"""
from alembic import op
import sqlalchemy as sa
import app.models.base


# revision identifiers, used by Alembic.
revision = 'cd73103ae9e0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cars',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('condition', sa.String(length=20), nullable=False),
    sa.Column('price_egp', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('body_type', sa.String(length=50), nullable=True),
    sa.Column('transmission', sa.String(length=50), nullable=True),
    sa.Column('fuel_type', sa.String(length=50), nullable=True),
    sa.Column('mileage_km', sa.Integer(), nullable=True),
    sa.Column('engine_capacity', sa.String(length=50), nullable=True),
    sa.Column('engine_power', sa.String(length=50), nullable=True),
    sa.Column('trim', sa.String(length=100), nullable=True),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('source_id', sa.String(length=100), nullable=True),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("condition IN ('new', 'used')", name=op.f('ck_cars_car_condition_check')),
    sa.CheckConstraint('mileage_km IS NULL OR mileage_km >= 0', name=op.f('ck_cars_car_mileage_non_negative_check')),
    sa.CheckConstraint('price_egp >= 0', name=op.f('ck_cars_car_price_positive_check')),
    sa.CheckConstraint('year >= 1900 AND year <= 2100', name=op.f('ck_cars_car_year_range_check')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cars')),
    sa.UniqueConstraint('source', 'source_id', name='uq_cars_source_source_id')
    )
    with op.batch_alter_table('cars', schema=None) as batch_op:
        batch_op.create_index('ix_cars_active', ['active'], unique=False)
        batch_op.create_index('ix_cars_body_type', ['body_type'], unique=False)
        batch_op.create_index('ix_cars_brand', ['brand'], unique=False)
        batch_op.create_index('ix_cars_brand_model', ['brand', 'model'], unique=False)
        batch_op.create_index('ix_cars_condition', ['condition'], unique=False)
        batch_op.create_index('ix_cars_model', ['model'], unique=False)
        batch_op.create_index('ix_cars_price_egp', ['price_egp'], unique=False)
        batch_op.create_index('ix_cars_transmission', ['transmission'], unique=False)
        batch_op.create_index('ix_cars_year', ['year'], unique=False)

    op.create_table('knowledge_documents',
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_documents'))
    )
    with op.batch_alter_table('knowledge_documents', schema=None) as batch_op:
        batch_op.create_index('ix_knowledge_documents_active', ['active'], unique=False)
        batch_op.create_index('ix_knowledge_documents_category', ['category'], unique=False)
        batch_op.create_index('ix_knowledge_documents_category_active', ['category', 'active'], unique=False)

    op.create_table('conversation_sessions',
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('preferences', app.models.base.PortableJSON(), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('selected_car_id', sa.Integer(), nullable=True),
    sa.Column('active_recommendation_snapshot_id', sa.Integer(), nullable=True),
    sa.Column('pending_action', app.models.base.PortableJSON(), nullable=True),
    sa.Column('status', sa.String(length=50), server_default='active', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['active_recommendation_snapshot_id'], ['recommendation_snapshots.id'], name='fk_conversation_sessions_active_rec_snapshot', ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['selected_car_id'], ['cars.id'], name='fk_conversation_sessions_selected_car_id_cars', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversation_sessions'))
    )
    with op.batch_alter_table('conversation_sessions', schema=None) as batch_op:
        batch_op.create_index('ix_conversation_sessions_status', ['status'], unique=False)

    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', app.models.base.GUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('user', 'assistant', 'system', 'tool')", name=op.f('ck_chat_messages_chat_message_role_check')),
    sa.ForeignKeyConstraint(['session_id'], ['conversation_sessions.id'], name='fk_chat_messages_session_id_conversation_sessions', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_messages'))
    )
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.create_index('ix_chat_messages_session_created', ['session_id', 'created_at'], unique=False)
        batch_op.create_index('ix_chat_messages_session_id', ['session_id'], unique=False)

    op.create_table('recommendation_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', app.models.base.GUID(), nullable=False),
    sa.Column('sequence_no', sa.Integer(), nullable=False),
    sa.Column('criteria', app.models.base.PortableJSON(), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('status', sa.String(length=50), server_default='active', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('sequence_no > 0', name=op.f('ck_recommendation_snapshots_rec_snapshot_sequence_no_check')),
    sa.ForeignKeyConstraint(['session_id'], ['conversation_sessions.id'], name='fk_recommendation_snapshots_session_id_conv_sessions', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recommendation_snapshots')),
    sa.UniqueConstraint('session_id', 'sequence_no', name='uq_rec_snapshots_session_sequence')
    )
    with op.batch_alter_table('recommendation_snapshots', schema=None) as batch_op:
        batch_op.create_index('ix_rec_snapshots_session_id', ['session_id'], unique=False)
        batch_op.create_index('ix_rec_snapshots_session_sequence', ['session_id', 'sequence_no'], unique=False)

    op.create_table('sales_leads',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', app.models.base.GUID(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=True),
    sa.Column('customer_name', sa.String(length=150), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('status', sa.String(length=30), server_default='NEW', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('NEW', 'CONTACTED', 'QUALIFIED', 'CLOSED_WON', 'CLOSED_LOST')", name=op.f('ck_sales_leads_sales_lead_status_check')),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], name='fk_sales_leads_car_id_cars', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['conversation_sessions.id'], name='fk_sales_leads_session_id_conv_sessions', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sales_leads')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_sales_leads_idempotency_key'))
    )
    with op.batch_alter_table('sales_leads', schema=None) as batch_op:
        batch_op.create_index('ix_sales_leads_car_id', ['car_id'], unique=False)
        batch_op.create_index('ix_sales_leads_session_id', ['session_id'], unique=False)
        batch_op.create_index('ix_sales_leads_session_status', ['session_id', 'status'], unique=False)
        batch_op.create_index('ix_sales_leads_status', ['status'], unique=False)

    op.create_table('test_drive_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', app.models.base.GUID(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('customer_name', sa.String(length=150), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('preferred_date', sa.Date(), nullable=False),
    sa.Column('preferred_time', sa.Time(), nullable=False),
    sa.Column('status', sa.String(length=30), server_default='NEW', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=100), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('NEW', 'CONFIRMED', 'COMPLETED', 'CANCELLED')", name=op.f('ck_test_drive_requests_test_drive_status_check')),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], name='fk_test_drive_requests_car_id_cars', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['session_id'], ['conversation_sessions.id'], name='fk_test_drive_requests_session_id_conv_sessions', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_test_drive_requests')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_test_drive_requests_idempotency_key'))
    )
    with op.batch_alter_table('test_drive_requests', schema=None) as batch_op:
        batch_op.create_index('ix_test_drive_requests_car_id', ['car_id'], unique=False)
        batch_op.create_index('ix_test_drive_requests_session_id', ['session_id'], unique=False)
        batch_op.create_index('ix_test_drive_requests_session_status', ['session_id', 'status'], unique=False)
        batch_op.create_index('ix_test_drive_requests_status', ['status'], unique=False)

    op.create_table('recommendation_snapshot_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('position > 0', name=op.f('ck_recommendation_snapshot_items_rec_snapshot_item_position_check')),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], name='fk_rec_snapshot_items_car_id_cars', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['snapshot_id'], ['recommendation_snapshots.id'], name='fk_rec_snapshot_items_snapshot_id_rec_snapshots', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recommendation_snapshot_items')),
    sa.UniqueConstraint('snapshot_id', 'car_id', name='uq_rec_snapshot_items_snapshot_car'),
    sa.UniqueConstraint('snapshot_id', 'position', name='uq_rec_snapshot_items_snapshot_position')
    )
    with op.batch_alter_table('recommendation_snapshot_items', schema=None) as batch_op:
        batch_op.create_index('ix_rec_snapshot_items_car_id', ['car_id'], unique=False)
        batch_op.create_index('ix_rec_snapshot_items_snapshot_id', ['snapshot_id'], unique=False)

    bind = op.get_bind()
    if bind.dialect.name == 'postgresql':
        for table in [
            'cars',
            'knowledge_documents',
            'conversation_sessions',
            'chat_messages',
            'recommendation_snapshots',
            'sales_leads',
            'test_drive_requests',
            'recommendation_snapshot_items',
        ]:
            op.execute(f'ALTER TABLE {table} ENABLE ROW LEVEL SECURITY;')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recommendation_snapshot_items', schema=None) as batch_op:
        batch_op.drop_index('ix_rec_snapshot_items_snapshot_id')
        batch_op.drop_index('ix_rec_snapshot_items_car_id')

    op.drop_table('recommendation_snapshot_items')
    with op.batch_alter_table('test_drive_requests', schema=None) as batch_op:
        batch_op.drop_index('ix_test_drive_requests_status')
        batch_op.drop_index('ix_test_drive_requests_session_status')
        batch_op.drop_index('ix_test_drive_requests_session_id')
        batch_op.drop_index('ix_test_drive_requests_car_id')

    op.drop_table('test_drive_requests')
    with op.batch_alter_table('sales_leads', schema=None) as batch_op:
        batch_op.drop_index('ix_sales_leads_status')
        batch_op.drop_index('ix_sales_leads_session_status')
        batch_op.drop_index('ix_sales_leads_session_id')
        batch_op.drop_index('ix_sales_leads_car_id')

    op.drop_table('sales_leads')
    with op.batch_alter_table('recommendation_snapshots', schema=None) as batch_op:
        batch_op.drop_index('ix_rec_snapshots_session_sequence')
        batch_op.drop_index('ix_rec_snapshots_session_id')

    op.drop_table('recommendation_snapshots')
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_index('ix_chat_messages_session_id')
        batch_op.drop_index('ix_chat_messages_session_created')

    op.drop_table('chat_messages')
    with op.batch_alter_table('conversation_sessions', schema=None) as batch_op:
        batch_op.drop_index('ix_conversation_sessions_status')

    op.drop_table('conversation_sessions')
    with op.batch_alter_table('knowledge_documents', schema=None) as batch_op:
        batch_op.drop_index('ix_knowledge_documents_category_active')
        batch_op.drop_index('ix_knowledge_documents_category')
        batch_op.drop_index('ix_knowledge_documents_active')

    op.drop_table('knowledge_documents')
    with op.batch_alter_table('cars', schema=None) as batch_op:
        batch_op.drop_index('ix_cars_year')
        batch_op.drop_index('ix_cars_transmission')
        batch_op.drop_index('ix_cars_price_egp')
        batch_op.drop_index('ix_cars_model')
        batch_op.drop_index('ix_cars_condition')
        batch_op.drop_index('ix_cars_brand_model')
        batch_op.drop_index('ix_cars_brand')
        batch_op.drop_index('ix_cars_body_type')
        batch_op.drop_index('ix_cars_active')

    op.drop_table('cars')
    # ### end Alembic commands ###
