"""create core dealership tables

Revision ID: e89ca79411a2
Revises: 
Create Date: 2026-09-09 17:07:59.819393

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e89ca79411a2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('first_name', sa.String(length=120), nullable=False),
    sa.Column('last_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customers_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_customers_phone'), ['phone'], unique=False)

    op.create_table('vehicles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('brand', sa.String(length=120), nullable=False),
    sa.Column('model', sa.String(length=160), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('condition', sa.String(length=16), nullable=False),
    sa.Column('price_egp', sa.BigInteger(), nullable=False),
    sa.Column('kilometers', sa.BigInteger(), nullable=True),
    sa.Column('fuel_type', sa.String(length=64), nullable=True),
    sa.Column('transmission_type', sa.String(length=32), nullable=False),
    sa.Column('engine_capacity_cc', sa.Integer(), nullable=True),
    sa.Column('body_type', sa.String(length=64), nullable=True),
    sa.Column('trim', sa.String(length=160), nullable=True),
    sa.Column('horsepower', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('color', sa.String(length=64), nullable=True),
    sa.Column('powertrain_type', sa.String(length=32), nullable=True),
    sa.Column('vin', sa.String(length=64), nullable=True),
    sa.Column('stock_number', sa.String(length=64), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('source_id', sa.String(length=255), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_quality_status', sa.String(length=64), nullable=False),
    sa.Column('data_quality_metadata', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("condition IN ('new', 'used')", name='ck_vehicles_condition'),
    sa.CheckConstraint('engine_capacity_cc IS NULL OR engine_capacity_cc > 0', name='ck_vehicles_engine_positive'),
    sa.CheckConstraint('horsepower IS NULL OR horsepower > 0', name='ck_vehicles_horsepower_positive'),
    sa.CheckConstraint('kilometers IS NULL OR kilometers >= 0', name='ck_vehicles_kilometers_nonnegative'),
    sa.CheckConstraint('price_egp >= 0', name='ck_vehicles_price_nonnegative'),
    sa.CheckConstraint('year >= 1900 AND year <= 2100', name='ck_vehicles_year_range'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_number'),
    sa.UniqueConstraint('vin')
    )
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.create_index('ix_vehicles_body_type', ['body_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicles_brand'), ['brand'], unique=False)
        batch_op.create_index('ix_vehicles_brand_model', ['brand', 'model'], unique=False)
        batch_op.create_index('ix_vehicles_brand_model_year', ['brand', 'model', 'year'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicles_condition'), ['condition'], unique=False)
        batch_op.create_index('ix_vehicles_condition_price', ['condition', 'price_egp'], unique=False)
        batch_op.create_index('ix_vehicles_fuel_type', ['fuel_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicles_model'), ['model'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicles_price_egp'), ['price_egp'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicles_source_id'), ['source_id'], unique=True)
        batch_op.create_index('ix_vehicles_transmission_type', ['transmission_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicles_year'), ['year'], unique=False)

    op.create_table('leads',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('vehicle_id', sa.Uuid(), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('new', 'contacted', 'qualified', 'negotiating', 'won', 'lost')", name='ck_leads_status'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_leads_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_leads_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_leads_vehicle_id'), ['vehicle_id'], unique=False)

    op.create_table('conversations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=True),
    sa.Column('lead_id', sa.Uuid(), nullable=True),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('open', 'closed')", name='ck_conversations_status'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversations_channel'), ['channel'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversations_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversations_lead_id'), ['lead_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversations_status'), ['status'], unique=False)

    op.create_table('messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('sender_type', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("sender_type IN ('customer', 'agent', 'system')", name='ck_messages_sender_type'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_conversation_id'), ['conversation_id'], unique=False)

    # Flask's backend role accesses these tables directly.  No public/anon RLS
    # policies are created, so the Supabase Data API cannot expose them.
    for table_name in ('vehicles', 'customers', 'leads', 'conversations', 'messages'):
        op.execute(f'ALTER TABLE public.{table_name} ENABLE ROW LEVEL SECURITY')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_conversation_id'))

    op.drop_table('messages')
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversations_status'))
        batch_op.drop_index(batch_op.f('ix_conversations_lead_id'))
        batch_op.drop_index(batch_op.f('ix_conversations_customer_id'))
        batch_op.drop_index(batch_op.f('ix_conversations_channel'))

    op.drop_table('conversations')
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leads_vehicle_id'))
        batch_op.drop_index(batch_op.f('ix_leads_status'))
        batch_op.drop_index(batch_op.f('ix_leads_customer_id'))

    op.drop_table('leads')
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vehicles_year'))
        batch_op.drop_index('ix_vehicles_transmission_type')
        batch_op.drop_index(batch_op.f('ix_vehicles_source_id'))
        batch_op.drop_index(batch_op.f('ix_vehicles_price_egp'))
        batch_op.drop_index(batch_op.f('ix_vehicles_model'))
        batch_op.drop_index('ix_vehicles_fuel_type')
        batch_op.drop_index('ix_vehicles_condition_price')
        batch_op.drop_index(batch_op.f('ix_vehicles_condition'))
        batch_op.drop_index('ix_vehicles_brand_model_year')
        batch_op.drop_index('ix_vehicles_brand_model')
        batch_op.drop_index(batch_op.f('ix_vehicles_brand'))
        batch_op.drop_index('ix_vehicles_body_type')

    op.drop_table('vehicles')
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customers_phone'))
        batch_op.drop_index(batch_op.f('ix_customers_email'))

    op.drop_table('customers')
    # ### end Alembic commands ###
